# Generated by Django 2.0.13 on 2019-05-24 07:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0002_auto_20190524_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
