# Generated by Django 2.0.13 on 2019-05-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0004_category_description_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(),
        ),
    ]
