# Generated by Django 2.0.13 on 2019-05-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0006_auto_20190529_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Катгория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
