# Generated by Django 2.0.13 on 2019-05-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0007_auto_20190529_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_detail',
            name='full_lesson_text',
            field=models.TextField(),
        ),
    ]
