# Generated by Django 2.0.13 on 2019-05-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0008_auto_20190529_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(verbose_name='Краткое описание урока'),
        ),
    ]
