# Generated by Django 2.0.13 on 2019-05-29 08:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0010_auto_20190529_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Краткое описание урока'),
        ),
    ]
