# Generated by Django 2.0.13 on 2019-05-30 10:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0012_lesson_full_lesson_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='full_lesson_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полный текст урока'),
        ),
    ]
